### PR TITLE
various nitpicks

### PR DESCRIPTION
**Pull request by Cobord**

### CODE REVIEW

**Comment by maxvonhippel** [comment]
Thanks @Cobord !  I made a few small changes and will merge in a separate PR.

This solves the bug you reported on Linux Mint Cinnamon, correct?  (In addition to the obvious code quality improvements?)

**Comment by Cobord** [comment]
No. As in #random, said that traced that to pyjwt

**Comment by maxvonhippel** [comment]
> No. As in #random, said that traced that to pyjwt

Right, gotcha, found the stack trace:

```
benchify benchify_test.py
ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/ammar/.local/bin/benchify", line 5, in <module>
    from benchify.main import analyze
  File "/home/ammar/.local/lib/python3.9/site-packages/benchify/main.py", line 4, in <module>
    import jwt
  File "/home/ammar/.local/lib/python3.9/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/home/ammar/.local/lib/python3.9/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/home/ammar/.local/lib/python3.9/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/home/ammar/.local/lib/python3.9/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/home/ammar/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/home/ammar/.local/lib/python3.9/site-packages/cryptography/hazmat/_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed
```

Looks like something to do with how we decode the token for `auth0`.

**Comment by Cobord** [comment]
Not on this end. Because I get a similar such Python API call failed from PyO3 when just doing import jwt in the REPL. Not the exact same "from cyptography.hazmat.bindings._rust import ..." above, but still one of those.

**Pull request closed without merging**
